"""Pytest configuration for maxima - generated by phoenix init."""

from __future__ import annotations

import pytest
from playwright.sync_api import Browser, BrowserContext, Page, sync_playwright


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BASE_URL = "https://maximaapparel.com"
DEFAULT_BROWSER = "chromium"


def _parser_has_option(parser, option_name: str) -> bool:
    option_groups = []
    anonymous = getattr(parser, "_anonymous", None)
    if anonymous is not None:
        option_groups.append(anonymous)
    option_groups.extend(getattr(parser, "_groups", []))

    for group in option_groups:
        for option in getattr(group, "options", []):
            if option_name in getattr(option, "_long_opts", []):
                return True
    return False


def _addoption_if_missing(parser, option_name: str, *aliases, **kwargs) -> None:
    if _parser_has_option(parser, option_name):
        return
    try:
        parser.addoption(option_name, *aliases, **kwargs)
    except ValueError as exc:
        if option_name not in str(exc):
            raise


def pytest_addoption(parser):
    _addoption_if_missing(
        parser,
        "--base-url",
        action="store",
        default=None,
        help="Base URL for Phoenix-generated tests when pytest-playwright is not installed.",
    )
    _addoption_if_missing(
        parser,
        "--browser-type",
        default=DEFAULT_BROWSER,
        choices=["chromium", "firefox", "webkit"],
        help="Browser to use",
    )
    _addoption_if_missing(
        parser,
        "--headless",
        action="store_true",
        default=True,
        help="Run headless",
    )


# ---------------------------------------------------------------------------
# Playwright fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def base_url(request) -> str:
    configured_base_url = request.config.getoption("--base-url", default=None)
    return configured_base_url or BASE_URL


@pytest.fixture(scope="session")
def playwright_instance():
    with sync_playwright() as pw:
        yield pw


@pytest.fixture(scope="session")
def browser_type_name(request) -> str:
    return request.config.getoption("--browser-type")


@pytest.fixture(scope="session")
def browser(playwright_instance, browser_type_name, request) -> Browser:
    headless = request.config.getoption("--headless")
    browser_type = getattr(playwright_instance, browser_type_name)
    b = browser_type.launch(headless=headless)
    yield b
    b.close()


@pytest.fixture
def context(browser) -> BrowserContext:
    ctx = browser.new_context()
    yield ctx
    ctx.close()


@pytest.fixture
def page(context) -> Page:
    p = context.new_page()
    yield p
    p.close()


# ---------------------------------------------------------------------------
# Authenticated page fixture - extend with your login logic
# ---------------------------------------------------------------------------

@pytest.fixture
def authenticated_page(page, base_url) -> Page:
    """Return a page that has been authenticated.

    Override this fixture with your application's login steps:

        page.goto(f"{base_url}/login")
        page.get_by_label("Username").fill("admin")
        page.get_by_label("Password").fill("admin123")
        page.get_by_role("button", name="Login").click()
        page.wait_for_url("**/dashboard")
    """
    # TODO: implement login
    return page


# ---------------------------------------------------------------------------
# Locator registry (multi-locator support)
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def locator_registry(tmp_path_factory):
    """Session-scoped registry that maps element names to LocatorBundles.

    Populated from locators/*.json at runtime if phoenix-core is installed.
    """
    try:
        from phoenix.locators.registry import LocatorRegistry

        registry = LocatorRegistry.load_all("locators/")
    except ImportError:
        registry = {}
    return registry
