"""Pytest configuration for orange — generated by phoenix init."""

from __future__ import annotations

import json
import os
import re
import time
from contextlib import suppress
from pathlib import Path

import pytest
from playwright.sync_api import Browser, BrowserContext, Page, sync_playwright

# Phoenix enterprise subsystems
try:
    from phoenix.pool import BrowserPool
    from phoenix.session_recovery import SessionRecovery
    from phoenix.dom_cache import DOMCache
    from phoenix.metrics import MetricsCollector
    from phoenix.execution.healing import HealingEngine
    from phoenix.execution.runtime_wrapper import get_runtime_integration, print_runtime_summary
    PHOENIX_AVAILABLE = True
except ImportError:
    PHOENIX_AVAILABLE = False

# Phoenix Intelligent Runtime integration
try:
    from phoenix.execution.intelligent_runtime import IntelligentRuntime
    INTELLIGENT_RUNTIME_AVAILABLE = True
except ImportError:
    INTELLIGENT_RUNTIME_AVAILABLE = False


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BASE_URL = os.environ.get(
    "APP_URL",
    "https://opensource-demo.orangehrmlive.com/web/index.php/auth/login",
)
DEFAULT_BROWSER = os.environ.get("PHOENIX_BROWSER", "chromium")
ACTION_TIMEOUT_MS = 30_000
NAVIGATION_TIMEOUT_MS = 60_000


def _parser_has_option(parser, option_name: str) -> bool:
    option_groups = []
    anonymous = getattr(parser, "_anonymous", None)
    if anonymous is not None:
        option_groups.append(anonymous)
    option_groups.extend(getattr(parser, "_groups", []))
    for group in option_groups:
        for option in getattr(group, "options", []):
            if option_name in getattr(option, "_long_opts", []):
                return True
    return False


def _addoption_if_missing(parser, option_name: str, *aliases, **kwargs) -> None:
    if _parser_has_option(parser, option_name):
        return
    try:
        parser.addoption(option_name, *aliases, **kwargs)
    except ValueError as exc:
        if option_name not in str(exc):
            raise


def pytest_addoption(parser):
    _addoption_if_missing(
        parser,
        "--base-url",
        action="store",
        default=None,
        help="Override APP_URL for this test run.",
    )
    _addoption_if_missing(
        parser,
        "--browser-type",
        default=DEFAULT_BROWSER,
        choices=["chromium", "firefox", "webkit"],
        help="Browser to use",
    )
    # --headed is owned by pytest-playwright; do not re-register it here.


# ---------------------------------------------------------------------------
# Playwright fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def base_url(request) -> str:
    return request.config.getoption("--base-url", default=None) or BASE_URL


@pytest.fixture(scope="session")
def playwright_instance():
    with sync_playwright() as pw:
        yield pw


@pytest.fixture(scope="session")
def browser_type_name(request) -> str:
    return request.config.getoption("--browser-type")


@pytest.fixture(scope="session")
def browser_type_launch_args(request):
    """Launch args — headed when --headed flag or PWHEADED=1 env var is set."""
    headed = request.config.getoption("--headed", default=False) or os.getenv("PWHEADED") == "1"
    return {
        "headless": not headed,
        "slow_mo": int(os.getenv("PWSLOWMO", "0")),
        "args": [
            "--disable-save-password-bubble",
            "--disable-features=PasswordManager",
        ],
    }


@pytest.fixture(scope="session")
def browser_context_args(browser_context_args):
    """Override context args to enforce a consistent viewport across all machines.

    The viewport is read from environment variables set by `phoenix run --viewport`
    or falls back to the project's .phoenixrc [run] settings (default 1920x1080).

    A fixed viewport ensures layout, element positions, and responsive breakpoints
    are identical on every laptop, desktop, and CI runner — making failures
    reproducible from a screenshot alone.
    """
    w = int(os.environ.get("PW_VIEWPORT_W", "1920"))
    h = int(os.environ.get("PW_VIEWPORT_H", "1080"))
    return {**browser_context_args, "viewport": {"width": w, "height": h}}


@pytest.fixture(scope="session")
def browser_pool():
    """Phoenix browser pool for efficient resource management."""
    if not PHOENIX_AVAILABLE:
        yield None
        return
    
    pool = BrowserPool(
        max_browsers=5,
        max_contexts_per_browser=5,
        max_pages_per_context=10,
        idle_timeout_ms=30000,
        enable_auto_cleanup=True
    )
    yield pool
    pool.cleanup_all()


@pytest.fixture(scope="session")
def session_recovery():
    """Phoenix session recovery for automatic session restoration."""
    if not PHOENIX_AVAILABLE:
        yield None
        return
    
    recovery = SessionRecovery(
        enable_auto_recovery=True,
        check_logout_indicators=True,
        save_session_state=True
    )
    yield recovery


@pytest.fixture(scope="session")
def dom_cache():
    """Phoenix DOM cache for performance optimization."""
    if not PHOENIX_AVAILABLE:
        yield None
        return
    
    cache = DOMCache(
        default_ttl_ms=30000,
        max_size_bytes=10485760,
        max_entries=100
    )
    yield cache


@pytest.fixture(scope="session")
def metrics_collector():
    """Phoenix metrics collector for runtime metrics."""
    if not PHOENIX_AVAILABLE:
        yield None
        return
    
    collector = MetricsCollector()
    yield collector


@pytest.fixture(scope="session")
def healing_engine():
    """Phoenix healing engine for automatic failure recovery."""
    if not PHOENIX_AVAILABLE:
        yield None
        return
    
    engine = HealingEngine()
    yield engine


@pytest.fixture(scope="session")
def browser(playwright_instance, browser_type_name, browser_type_launch_args, browser_pool) -> Browser:
    """Browser fixture - uses browser pool if available."""
    if PHOENIX_AVAILABLE and browser_pool:
        browser_id, browser = browser_pool.get_browser(playwright_instance)
        yield browser
        # Cleanup handled by browser pool
    else:
        browser_type = getattr(playwright_instance, browser_type_name)
        b = browser_type.launch(**browser_type_launch_args)
        yield b
        with suppress(Exception):
            b.close()


@pytest.fixture
def context(browser, browser_pool, session_recovery) -> BrowserContext:
    """Context fixture - uses browser pool and session recovery if available."""
    if PHOENIX_AVAILABLE and browser_pool:
        # Get context from browser pool
        browser_id = "browser_0"  # Assume first browser
        context_id, ctx = browser_pool.get_context(browser_id, browser)
        ctx.set_default_timeout(ACTION_TIMEOUT_MS)
        ctx.set_default_navigation_timeout(NAVIGATION_TIMEOUT_MS)
        
        # Save session state if session recovery is available
        if session_recovery:
            session_recovery.save_session("default_session", ctx)
        
        yield ctx
        # Cleanup handled by browser pool
    else:
        ctx = browser.new_context()
        ctx.set_default_timeout(ACTION_TIMEOUT_MS)
        ctx.set_default_navigation_timeout(NAVIGATION_TIMEOUT_MS)
        yield ctx
        with suppress(Exception):
            ctx.close()


@pytest.fixture
def page(context, browser_pool, dom_cache, healing_engine, intelligent_runtime, request) -> Page:
    """Playwright Page fixture with automatic Intelligent Runtime integration.
    
    This fixture automatically wraps the standard Playwright page with intelligent
    runtime capabilities when IntelligentRuntime is available, ensuring:
    - DOM Snapshot reuse decisions
    - Locator Repository integration
    - Healing Engine availability
    - Runtime Metrics collection
    - Timeline tracking
    
    The integration is transparent - tests don't need to change their code.
    """
    p = None
    use_browser_pool = PHOENIX_AVAILABLE and browser_pool
    
    if use_browser_pool:
        # Get page from browser pool
        browser_id = "browser_0"  # Assume first browser
        page_id, p = browser_pool.get_page(context, browser_id)
        p.set_default_timeout(ACTION_TIMEOUT_MS)
        p.set_default_navigation_timeout(NAVIGATION_TIMEOUT_MS)
        p.on("dialog", lambda dialog: dialog.dismiss())
        
        # Store DOM cache reference on page for use in tests
        p._phoenix_dom_cache = dom_cache
        p._phoenix_healing_engine = healing_engine
    else:
        p = context.new_page()
        p.set_default_timeout(ACTION_TIMEOUT_MS)
        p.set_default_navigation_timeout(NAVIGATION_TIMEOUT_MS)
        p.on("dialog", lambda dialog: dialog.dismiss())
    
    # Always attempt intelligent page wrapping if IntelligentRuntime is available
    if intelligent_runtime:
        try:
            from phoenix.execution.intelligent_page import create_intelligent_page as create_intelligent_page
            test_name = request.node.name if hasattr(request, 'node') else "orange_test"
            execution_id = getattr(intelligent_runtime, 'execution_id', '')
            project_name = getattr(intelligent_runtime, 'project_name', 'orange')
            
            print(f"[INTELLIGENT PAGE] Wrapping page for test: {test_name}")
            print(f"[INTELLIGENT PAGE] Project: {project_name}, Execution ID: {execution_id}")
            
            p = create_intelligent_page(
                page=p,
                intelligent_runtime=intelligent_runtime,
                project_name=project_name,
                test_name=test_name,
                execution_id=execution_id
            )
            
            print(f"[INTELLIGENT PAGE] Page successfully wrapped with intelligent runtime")
        except Exception as e:
            print(f"[INTELLIGENT PAGE] Failed to wrap page with intelligent runtime: {e}")
            print(f"[INTELLIGENT PAGE] Falling back to standard Playwright page")
            # Continue with standard page if wrapping fails
    else:
        print("[INTELLIGENT PAGE] Intelligent Runtime not available, using standard Playwright page")
    
    yield p
    
    # Cleanup
    if not use_browser_pool:
        with suppress(Exception):
            p.close()


# ---------------------------------------------------------------------------
# Module-aware locator registry
# ---------------------------------------------------------------------------

def _module_from_path(path: Path) -> str:
    """Derive module name from test file path.

    tests/login/test_login.py  → "login"
    tests/checkout/test_...py  → "checkout"
    """
    parts = path.parts
    try:
        tests_idx = parts.index("tests")
        if tests_idx + 1 < len(parts):
            return parts[tests_idx + 1]
    except ValueError:
        pass
    return path.stem.replace("test_", "")


@pytest.fixture(scope="module")
def locator_registry(request):
    """Module-scoped registry loaded from locators/<module>.json."""
    module = _module_from_path(Path(request.fspath))
    loc_path = Path("locators") / f"{module}.json"
    try:
        from phoenix.locators.registry import LocatorRegistry
        if loc_path.exists():
            return LocatorRegistry.load_page(loc_path)
        return LocatorRegistry.load_all("locators/")
    except ImportError:
        return {}


# ---------------------------------------------------------------------------
# Module-aware test data fixture
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def test_data(request) -> dict:
    """Module-scoped fixture that loads test_data/<module>.json."""
    module = _module_from_path(Path(request.fspath))
    data_path = Path("test_data") / f"{module}.json"
    if data_path.exists():
        try:
            return json.loads(data_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass
    return {"scenarios": [], "edge_cases": []}


# ---------------------------------------------------------------------------
# Rich failure hook — plain-English summary + full technical detail
# ---------------------------------------------------------------------------

@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    """Capture rich failure detail and attach to pytest-html report.

    For every failed test the report contains (in order):
      1. Plain-English summary (what went wrong, no code)
      2. Full-page screenshot at the moment of failure
      3. Page URL and title
      4. Browser console errors
      5. Full Python traceback (inside a collapsible section)
    """
    outcome = yield
    report = outcome.get_result()

    if report.when != "call" or not report.failed:
        return

    page_fixture = item.funcargs.get("page") or item.funcargs.get("authenticated_page")
    if page_fixture is None:
        return

    extras = getattr(report, "extras", [])
    try:
        import pytest_html  # noqa: F401
        from pytest_html import extras as _extras
    except ImportError:
        _extras = None

    # 1. Screenshot
    screenshots_dir = Path("reports") / "screenshots"
    screenshots_dir.mkdir(parents=True, exist_ok=True)
    safe_name = re.sub(r"[^\w\-]", "_", item.nodeid)
    screenshot_path = screenshots_dir / f"{safe_name}.png"
    screenshot_taken = False
    with suppress(Exception):
        page_fixture.screenshot(path=str(screenshot_path), full_page=True)
        screenshot_taken = True
        report.screenshots = [str(screenshot_path)]

    # 2. Plain-English summary
    try:
        from phoenix.execution.failure_reporter import translate_error
        plain_summary = translate_error(
            report.longrepr.reprcrash.message
            if hasattr(report.longrepr, "reprcrash")
            else Exception(str(report.longreprtext)[:200])
        )
    except Exception:
        plain_summary = ""

    # 3. Page context
    page_url = ""
    page_title = ""
    with suppress(Exception):
        page_url = page_fixture.url
        page_title = page_fixture.title()

    # 4. Console errors
    console_errors: list = []
    with suppress(Exception):
        # collect errors logged via page.on("console", ...) if set up
        console_errors = getattr(page_fixture, "_phoenix_console_errors", [])

    # Build pytest-html extras
    if _extras:
        if plain_summary:
            extras.append(_extras.text(f"⚠ {plain_summary}", name="What happened"))
        if screenshot_taken:
            extras.append(_extras.image(str(screenshot_path), name="Screenshot"))
        if page_url:
            extras.append(_extras.text(f"URL:   {page_url}\nTitle: {page_title}", name="Page context"))
        if console_errors:
            extras.append(_extras.text("\n".join(console_errors), name="Console errors"))
        traceback_text = str(report.longreprtext) if hasattr(report, "longreprtext") else ""
        if traceback_text:
            extras.append(_extras.text(traceback_text, name="Technical detail (traceback)"))
        report.extras = extras


# ---------------------------------------------------------------------------
# Phoenix Runtime Summary Hook
# ---------------------------------------------------------------------------

def pytest_sessionfinish(session, exitstatus):
    """Print Phoenix runtime summary at the end of test session."""
    if PHOENIX_AVAILABLE:
        try:
            print_runtime_summary()
        except Exception:
            pass  # Runtime wrapper not available


# ---------------------------------------------------------------------------
# Phoenix Runtime Integration Fixture
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def phoenix_runtime():
    """Phoenix runtime integration for enterprise subsystem visibility."""
    if PHOENIX_AVAILABLE:
        try:
            return get_runtime_integration()
        except Exception:
            pass
    return None


# intelligent_runtime fixture is now provided by root conftest.py
# This ensures consistent intelligent runtime integration across all projects
# The standard page fixture now automatically wraps with intelligent runtime
# so separate intelligent_page fixture is no longer needed


# ---------------------------------------------------------------------------
# Authenticated page fixture — extend with your login logic
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Authenticated page fixture — provided by fixtures/auth.py
# ---------------------------------------------------------------------------
# The real authenticated_page is defined in fixtures/auth.py (session-scoped
# storage state, one login for the whole run).  We re-export it here so tests
# that only import conftest still get the fixture without a second login.

try:
    from fixtures.auth import (  # noqa: F401  (re-exported for pytest fixture resolution)
        auth_storage_state,
        authenticated_context,
        authenticated_page,
    )
except ImportError:
    # Fallback: fixtures/auth.py not generated yet (e.g. flat layout project).
    # Provides an unauthenticated page so tests at least import cleanly.
    @pytest.fixture
    def authenticated_page(page: Page) -> Page:  # type: ignore[no-redef]
        """Stub — replace with a real auth fixture or generate with phoenix init --pom."""
        return page

