"""Pytest configuration for skylark — generated by phoenix init."""

from __future__ import annotations

import json
import os
import re
from contextlib import suppress
from datetime import datetime
from pathlib import Path

import pytest
from playwright.sync_api import Browser, BrowserContext, Page, sync_playwright

# Load environment variables from .env files
try:
    from dotenv import load_dotenv
    # Load .env.local first (takes precedence), then .env
    load_dotenv(Path(__file__).parent / ".env.local", override=True)
    load_dotenv(Path(__file__).parent / ".env", override=False)
    print("[CONFTEST] Loaded environment variables from .env files")
except ImportError:
    print("[CONFTEST] python-dotenv not installed, .env files not loaded")
except Exception as e:
    print(f"[CONFTEST] Failed to load .env files: {e}")

# Phoenix Intelligent Runtime integration
try:
    from phoenix.execution.intelligent_runtime import IntelligentRuntime
    from phoenix.execution.intelligent_page import create_intelligent_page
    INTELLIGENT_RUNTIME_AVAILABLE = True
except ImportError:
    INTELLIGENT_RUNTIME_AVAILABLE = False

# Global variable to store intelligent_runtime instance for session finish hook
_intelligent_runtime_instance = None


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

BASE_URL = os.environ.get("APP_URL", "https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
DEFAULT_BROWSER = os.environ.get("PHOENIX_BROWSER", "chromium")
ACTION_TIMEOUT_MS = 30_000
NAVIGATION_TIMEOUT_MS = 60_000


def _parser_has_option(parser, option_name: str) -> bool:
    option_groups = []
    anonymous = getattr(parser, "_anonymous", None)
    if anonymous is not None:
        option_groups.append(anonymous)
    option_groups.extend(getattr(parser, "_groups", []))
    for group in option_groups:
        for option in getattr(group, "options", []):
            if option_name in getattr(option, "_long_opts", []):
                return True
    return False


def _addoption_if_missing(parser, option_name: str, *aliases, **kwargs) -> None:
    if _parser_has_option(parser, option_name):
        return
    try:
        parser.addoption(option_name, *aliases, **kwargs)
    except ValueError as exc:
        if option_name not in str(exc):
            raise


def pytest_addoption(parser):
    _addoption_if_missing(
        parser,
        "--base-url",
        action="store",
        default=None,
        help="Override APP_URL for this test run.",
    )
    _addoption_if_missing(
        parser,
        "--browser-type",
        default=DEFAULT_BROWSER,
        choices=["chromium", "firefox", "webkit"],
        help="Browser to use",
    )
    # --headed is owned by pytest-playwright; do not re-register it here.


# ---------------------------------------------------------------------------
# Playwright fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def base_url(request) -> str:
    return request.config.getoption("--base-url", default=None) or BASE_URL


@pytest.fixture(scope="session")
def playwright_instance():
    with sync_playwright() as pw:
        yield pw


@pytest.fixture(scope="session")
def browser_type_name(request) -> str:
    return request.config.getoption("--browser-type")


@pytest.fixture(scope="session")
def browser_type_launch_args(request):
    """Launch args — headed when --headed flag or PWHEADED=1 env var is set."""
    headed = request.config.getoption("--headed", default=False) or os.getenv("PWHEADED") == "1"
    return {
        "headless": not headed,
        "slow_mo": int(os.getenv("PWSLOWMO", "0")),
        "args": [
            "--disable-save-password-bubble",
            "--disable-features=PasswordManager",
        ],
    }


@pytest.fixture(scope="session")
def browser_context_args(browser_context_args):
    """Override context args to enforce a consistent viewport across all machines.

    The viewport is read from environment variables set by `phoenix run --viewport`
    or falls back to the project's .phoenixrc [run] settings (default 1920x1080).

    A fixed viewport ensures layout, element positions, and responsive breakpoints
    are identical on every laptop, desktop, and CI runner — making failures
    reproducible from a screenshot alone.
    """
    w = int(os.environ.get("PW_VIEWPORT_W", "1920"))
    h = int(os.environ.get("PW_VIEWPORT_H", "1080"))
    return {**browser_context_args, "viewport": {"width": w, "height": h}}


@pytest.fixture(scope="session")
def browser(playwright_instance, browser_type_name, browser_type_launch_args) -> Browser:
    browser_type = getattr(playwright_instance, browser_type_name)
    b = browser_type.launch(**browser_type_launch_args)
    yield b
    with suppress(Exception):
        b.close()


@pytest.fixture
def context(browser) -> BrowserContext:
    ctx = browser.new_context()
    ctx.set_default_timeout(ACTION_TIMEOUT_MS)
    ctx.set_default_navigation_timeout(NAVIGATION_TIMEOUT_MS)
    yield ctx
    with suppress(Exception):
        ctx.close()


@pytest.fixture
def page(context) -> Page:
    p = context.new_page()
    p.set_default_timeout(ACTION_TIMEOUT_MS)
    p.set_default_navigation_timeout(NAVIGATION_TIMEOUT_MS)
    p.on("dialog", lambda dialog: dialog.dismiss())
    yield p
    with suppress(Exception):
        p.close()


# ---------------------------------------------------------------------------
# Module-aware locator registry
# ---------------------------------------------------------------------------

def _module_from_path(path: Path) -> str:
    """Derive module name from test file path.

    tests/login/test_login.py  → "login"
    tests/checkout/test_...py  → "checkout"
    """
    parts = path.parts
    try:
        tests_idx = parts.index("tests")
        if tests_idx + 1 < len(parts):
            return parts[tests_idx + 1]
    except ValueError:
        pass
    return path.stem.replace("test_", "")


@pytest.fixture(scope="module")
def locator_registry(request):
    """Module-scoped registry loaded from locators/<module>.json."""
    module = _module_from_path(Path(request.fspath))
    loc_path = Path("locators") / f"{module}.json"
    try:
        from phoenix.locators.registry import LocatorRegistry
        if loc_path.exists():
            return LocatorRegistry.load_page(loc_path)
        return LocatorRegistry.load_all("locators/")
    except ImportError:
        return {}


# ---------------------------------------------------------------------------
# Module-aware test data fixture
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def test_data(request) -> dict:
    """Module-scoped fixture that loads test_data/<module>.json."""
    module = _module_from_path(Path(request.fspath))
    data_path = Path("test_data") / f"{module}.json"
    if data_path.exists():
        try:
            return json.loads(data_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass
    return {"scenarios": [], "edge_cases": []}


# ---------------------------------------------------------------------------
# Phoenix Intelligent Runtime integration
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def intelligent_runtime():
    """IntelligentRuntime instance for production test execution.
    
    This fixture loads the IntelligentRuntime state that was created by
    TestRunner before spawning the pytest subprocess. The state is stored
    in phoenix_runtime/.execution_context.json.
    """
    global _intelligent_runtime_instance
    
    if not INTELLIGENT_RUNTIME_AVAILABLE:
        print("[INTELLIGENT RUNTIME] Intelligent Runtime not available - imports failed")
        return None
    
    # Use absolute path to ensure consistent location
    current_dir = Path(os.getcwd())
    # Use the main project directory's phoenix_runtime for evidence tracking
    # Go up to find the main project directory (Phoenix-SmartAutomation)
    parent_dir = current_dir
    while parent_dir.name != "Phoenix-SmartAutomation" and parent_dir.parent != parent_dir:
        parent_dir = parent_dir.parent
    base_dir = parent_dir / "phoenix_runtime"
    
    # Try to load execution context from TestRunner
    execution_context_path = base_dir / ".execution_context.json"
    
    print(f"[INTELLIGENT RUNTIME] Execution context path: {execution_context_path}")
    print(f"[INTELLIGENT RUNTIME] Execution context exists: {execution_context_path.exists()}")
    
    if execution_context_path.exists():
        try:
            with open(execution_context_path, 'r', encoding='utf-8') as f:
                context = json.load(f)
            
            execution_id = context.get("execution_id")
            project_name = context.get("project_name", "default")
            enable_intelligent = context.get("enable_intelligent_runtime", True)
            enable_healing = context.get("enable_healing", True)
            
            if not enable_intelligent:
                print("[INTELLIGENT RUNTIME] Intelligent Runtime disabled in execution context")
                return None
            
            # Recreate IntelligentRuntime with the same configuration
            intelligent_runtime = IntelligentRuntime(
                base_dir=str(base_dir),
                project_name=project_name,
                enable_cache=True,
                enable_repository=True,
                enable_diff=True,
                enable_healing=enable_healing,
                enable_metrics=True,
                enable_timeline=True,
                enable_semantic=True
            )
            
            # Restore execution state
            intelligent_runtime.execution_id = execution_id
            intelligent_runtime.test_name = context.get("test_name", "default")
            
            # Start execution tracking with the existing execution ID
            intelligent_runtime.start_execution(intelligent_runtime.test_name)
            
            # Ensure runtime_evidence is initialized
            if intelligent_runtime.runtime_evidence is None:
                print("[INTELLIGENT RUNTIME] Runtime evidence was None, re-initializing")
                from phoenix.execution.intelligent_runtime import RuntimeEvidence
                intelligent_runtime.runtime_evidence = RuntimeEvidence(
                    execution_id=execution_id,
                    project_name=project_name,
                    test_name=intelligent_runtime.test_name,
                    timestamp=datetime.now().isoformat()
                )
            
            # Store globally for session finish hook
            _intelligent_runtime_instance = intelligent_runtime
            
            print(f"[INTELLIGENT RUNTIME] Loaded from execution context: {execution_id}")
            print(f"[INTELLIGENT RUNTIME] Project: {project_name}")
            print(f"[INTELLIGENT RUNTIME] Intelligent Runtime enabled and ready")
            
            return intelligent_runtime
            
        except Exception as e:
            print(f"[INTELLIGENT RUNTIME] Failed to load execution context: {e}")
            return None
    
    # Fallback: create new IntelligentRuntime instance if phoenix_runtime doesn't exist
    if not base_dir.exists():
        base_dir.mkdir(parents=True, exist_ok=True)
        print(f"[INTELLIGENT RUNTIME] Created phoenix_runtime directory: {base_dir}")
    
    print("[INTELLIGENT RUNTIME] No execution context found, creating new instance")
    try:
        intelligent_runtime = IntelligentRuntime(
            base_dir=str(base_dir),
            project_name="skylark",
            enable_cache=True,
            enable_repository=True,
            enable_diff=True,
            enable_healing=True,
            enable_metrics=True,
            enable_timeline=True,
            enable_semantic=True
        )
        
        # Store globally for session finish hook
        _intelligent_runtime_instance = intelligent_runtime
        
        # Initialize runtime evidence
        from phoenix.execution.intelligent_runtime import RuntimeEvidence
        intelligent_runtime.runtime_evidence = RuntimeEvidence(
            execution_id=intelligent_runtime.execution_id or "manual",
            project_name="skylark",
            test_name="manual",
            timestamp=datetime.now().isoformat()
        )
        
        print("[INTELLIGENT RUNTIME] Created new IntelligentRuntime instance")
        return intelligent_runtime
    except Exception as e:
        print(f"[INTELLIGENT RUNTIME] Failed to create IntelligentRuntime: {e}")
        return None


@pytest.fixture(scope="function")
def intelligent_page(page, intelligent_runtime, request):
    """Playwright Page wrapper with IntelligentRuntime integration.
    
    This fixture wraps the standard Playwright page with intelligent
    decision-making for DOM reuse, MCP calls, locator healing, and
    runtime evidence collection.
    
    Usage in tests:
        def test_example(intelligent_page):
            intelligent_page.goto("https://example.com")
            intelligent_page.click("#submit")
    """
    if not intelligent_runtime:
        # If IntelligentRuntime is not available, return standard page
        return page
    
    # Get test name from request node
    test_name = request.node.name if hasattr(request, 'node') else "unknown"
    project_name = intelligent_runtime.project_name
    execution_id = intelligent_runtime.execution_id or "unknown"
    
    # Create intelligent page wrapper
    wrapped_page = create_intelligent_page(
        page=page,
        intelligent_runtime=intelligent_runtime,
        project_name=project_name,
        test_name=test_name,
        execution_id=execution_id
    )
    
    return wrapped_page


def pytest_sessionfinish(session, exitstatus):
    """Print Phoenix runtime summary at the end of test session."""
    # Call IntelligentRuntime end_execution to save evidence
    global _intelligent_runtime_instance
    
    if _intelligent_runtime_instance:
        try:
            status = "passed" if exitstatus == 0 else "failed"
            _intelligent_runtime_instance.end_execution(status=status)
            
            # Print summary for verification
            if hasattr(_intelligent_runtime_instance, 'print_summary'):
                _intelligent_runtime_instance.print_summary()
        except Exception as e:
            print(f"[INTELLIGENT RUNTIME] Failed to end execution: {e}")
            import traceback
            traceback.print_exc()


# ---------------------------------------------------------------------------
# Rich failure hook — plain-English summary + full technical detail
# ---------------------------------------------------------------------------

@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    """Capture rich failure detail and attach to pytest-html report.

    For every failed test the report contains (in order):
      1. Plain-English summary (what went wrong, no code)
      2. Full-page screenshot at the moment of failure
      3. Page URL and title
      4. Browser console errors
      5. Full Python traceback (inside a collapsible section)
    """
    outcome = yield
    report = outcome.get_result()

    if report.when != "call" or not report.failed:
        return

    page_fixture = item.funcargs.get("page") or item.funcargs.get("authenticated_page")
    if page_fixture is None:
        return

    extras = getattr(report, "extras", [])
    try:
        import pytest_html  # noqa: F401
        from pytest_html import extras as _extras
    except ImportError:
        _extras = None

    # 1. Screenshot
    screenshots_dir = Path("reports") / "screenshots"
    screenshots_dir.mkdir(parents=True, exist_ok=True)
    safe_name = re.sub(r"[^\w\-]", "_", item.nodeid)
    screenshot_path = screenshots_dir / f"{safe_name}.png"
    screenshot_taken = False
    with suppress(Exception):
        page_fixture.screenshot(path=str(screenshot_path), full_page=True)
        screenshot_taken = True
        report.screenshots = [str(screenshot_path)]

    # 2. Plain-English summary
    try:
        from phoenix.execution.failure_reporter import translate_error
        plain_summary = translate_error(
            report.longrepr.reprcrash.message
            if hasattr(report.longrepr, "reprcrash")
            else Exception(str(report.longreprtext)[:200])
        )
    except Exception:
        plain_summary = ""

    # 3. Page context
    page_url = ""
    page_title = ""
    with suppress(Exception):
        page_url = page_fixture.url
        page_title = page_fixture.title()

    # 4. Console errors
    console_errors: list = []
    with suppress(Exception):
        # collect errors logged via page.on("console", ...) if set up
        console_errors = getattr(page_fixture, "_phoenix_console_errors", [])

    # Build pytest-html extras
    if _extras:
        if plain_summary:
            extras.append(_extras.text(f"⚠ {plain_summary}", name="What happened"))
        if screenshot_taken:
            extras.append(_extras.image(str(screenshot_path), name="Screenshot"))
        if page_url:
            extras.append(_extras.text(f"URL:   {page_url}\nTitle: {page_title}", name="Page context"))
        if console_errors:
            extras.append(_extras.text("\n".join(console_errors), name="Console errors"))
        traceback_text = str(report.longreprtext) if hasattr(report, "longreprtext") else ""
        if traceback_text:
            extras.append(_extras.text(traceback_text, name="Technical detail (traceback)"))
        report.extras = extras


# ---------------------------------------------------------------------------
# Authenticated page fixture — extend with your login logic
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Authenticated page fixture — provided by fixtures/auth.py
# ---------------------------------------------------------------------------
# The real authenticated_page is defined in fixtures/auth.py (session-scoped
# storage state, one login for the whole run).  We re-export it here so tests
# that only import conftest still get the fixture without a second login.

try:
    from fixtures.auth import (  # noqa: F401  (re-exported for pytest fixture resolution)
        auth_storage_state,
        authenticated_context,
        authenticated_page,
    )
except ImportError:
    # Fallback: fixtures/auth.py not generated yet (e.g. flat layout project).
    # Provides an unauthenticated page so tests at least import cleanly.
    @pytest.fixture
    def authenticated_page(page: Page) -> Page:  # type: ignore[no-redef]
        """Stub — replace with a real auth fixture or generate with phoenix init --pom."""
        return page

